services:
  - type: web
    name: portfolio
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y build-essential python3-dev libev-dev
      pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
